version: '3.8'

services:
  frontend:
    build: ./frontend
    ports:
      - "80:80"
    depends_on:
      - backend

  backend:
    build: ./backend
    ports:
      - "3000:3000"
    environment:
      - DB_HOST=postgres
      - DB_PORT=5432
      - DB_USER=salon
      - DB_PASSWORD=salon
      - DB_NAME=beautyflow
    depends_on:
      - postgres

  postgres:
    image: postgres:14
    ports:
      - "5432:5432"
    environment:
      - POSTGRES_USER=salon
      - POSTGRES_PASSWORD=salon
      - POSTGRES_DB=beautyflow
    volumes:
      - postgres_data:/var/lib/postgresql/data

volumes:
  postgres_data: